### ISSUE TITLE
SVG is not being displayed

### ISSUE THREAD

**Issue by ReazerDev** [SergeyMell/nativescript-plugins#19]
When I'm trying to show an svg file from a URL, nothing get's displayed and I get this error:
`ERROR TypeError: ___WEBPACK_IMPORTED_MODULE_0__.fromUrl(...).then is not a function`

Calling fromUrl in the ts file, I get this error
`ERROR TypeError: (0 , _sergeymell_nativescript_svg__WEBPACK_IMPORTED_MODULE_1__.fromUrl)(...).then is not a function`

when I use `.then`:
`fromUrl(URL).then(res => {
      console.log(res);
  });`
  
  Console logging the fromURL, without the `.then`, it prints an epmty object `{}`

**Comment by SergeyMell** [comment]
Closed via #20
